from All_events.message_suprimer import add_event_message_suprimer
from All_events.reaction import add_event_reaction
from All_events.message import add_event_on_message
from All_events.end import add_event_disconecte
from All_events.all_events import add_all_events